include:
  # --- Standard Firmware Builds ---
  
  # 1. Dongle Unit
  - board: seeeduino_xiao_ble//zmk
    shield: totem_dongle

  # 2. Left Keyboard Half
  - board: seeeduino_xiao_ble//zmk
    shield: totem_left

  # 3. Right Keyboard Half
  - board: seeeduino_xiao_ble//zmk
    shield: totem_right

  # --- Settings Reset Builds ---

  # 4. Settings Reset for Seeed XIAO BLE
  - board: seeeduino_xiao_ble//zmk
    shield: settings_reset